# ?? ??: ?? ?????? ????? ???? ??
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/kot_blog_db}  # .env? DB_URL? ????, ??? ??? ??
    username: ${DB_USERNAME:root}                           # .env? DB_USERNAME? ??
    password: ${DB_PASSWORD:57575han}                       # .env? DB_PASSWORD? ??
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
  security:
    csrf:
      enabled: false              # CSRF ?? ???? (API ?? ? ?? ?????)
  main:
    allow-bean-definition-overriding: true  # Bean ?? ????? ??

server:
  port: ${SERVER_PORT:8888}       # ?? ??? ?? ??? ?? ???? ??
  error:
    whitelabel:
      enabled: false

# ?? ??: ???? ???? ?? ??
logging:
  level:
    org.hibernate.SQL: info         # SQL ??? info ???? ??
    springframework.transaction: info  # ???? ?? ??? info ???? ??

---
# ?? ?? ??: dev ????? ???? ? ??
#spring.config.activate.on-profile: dev

test:
  a: 100  # ?? ???? ??? ? a
  b: 100  # ?? ???? ??? ? b

---